CREATE TABLE POST (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    LAST_MODIFIED DATE NOT NULL,
    SUMMARY TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CONSTRAINT PK_POST PRIMARY KEY (ID),
    CONSTRAINT U_POST_TITLE UNIQUE (TITLE)
);

CREATE TABLE POST_TAG (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ID_POST BIGINT NOT NULL,
    ID_TAG BIGINT NOT NULL,
    CONSTRAINT PK_POST_TAG PRIMARY KEY (ID),
    CONSTRAINT U_POST_TAG_FKS UNIQUE (ID_POST, ID_TAG),
    CONSTRAINT FK_POST_TAG_POST FOREIGN KEY (ID_POST) REFERENCES POST (ID),
    CONSTRAINT FK_POST_TAG_TAG FOREIGN KEY (ID_TAG) REFERENCES TAG (ID)
);

CREATE TABLE POST_AUTHOR (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ID_POST BIGINT NOT NULL,
    ID_AUTHOR BIGINT NOT NULL,
    CONSTRAINT PK_POST_AUTHOR PRIMARY KEY (ID),
    CONSTRAINT U_POST_AUTHOR_FKS UNIQUE (ID_POST, ID_AUTHOR),
    CONSTRAINT FK_POST_AUTHOR_POST FOREIGN KEY (ID_POST) REFERENCES POST (ID),
    CONSTRAINT FK_POST_AUTHOR_AUTHOR FOREIGN KEY (ID_AUTHOR) REFERENCES AUTHOR (ID)
);
